import { StyleSheet } from 'react-native';

export const multiplayerStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  screen: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 14,
  },
  introCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E6D5C3',
    padding: 16,
    gap: 8,
  },
  introTitle: {
    fontSize: 18,
    color: '#5A3A0A',
    textAlign: 'center',
  },
  introBody: {
    fontSize: 14,
    lineHeight: 20,
    color: '#6B5344',
    textAlign: 'center',
  },
  sectionLabel: {
    fontSize: 13,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.25)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    marginTop: 4,
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionChip: {
    minWidth: 72,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.35)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.45)',
    alignItems: 'center',
  },
  optionChipActive: {
    backgroundColor: '#FFD54F',
    borderColor: '#E6AC00',
  },
  optionChipDisabled: {
    opacity: 0.45,
  },
  optionChipText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  optionChipTextActive: {
    color: '#5A3A0A',
  },
  optionChipTextDisabled: {
    color: 'rgba(255,255,255,0.7)',
  },
  timerModeCard: {
    borderRadius: 18,
    borderWidth: 2,
    padding: 14,
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderColor: 'rgba(255,255,255,0.4)',
  },
  timerModeCardActive: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderColor: '#2A93F4',
  },
  timerModeTitle: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  timerModeTitleActive: {
    color: '#1565C0',
  },
  timerModeBody: {
    fontSize: 13,
    lineHeight: 18,
    color: 'rgba(255,255,255,0.9)',
  },
  timerModeBodyActive: {
    color: '#2E5F8A',
  },
  primaryBtn: {
    marginTop: 8,
    backgroundColor: '#72BE2C',
    borderWidth: 2,
    borderColor: '#4E961B',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#2D5012',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.24,
    shadowRadius: 0,
    elevation: 4,
  },
  primaryBtnBlue: {
    backgroundColor: '#2A93F4',
    borderColor: '#1B6ED4',
    shadowColor: '#0A3D66',
  },
  primaryBtnPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  primaryBtnDisabled: {
    opacity: 0.55,
  },
  primaryBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    letterSpacing: 0.4,
  },
  secondaryBtn: {
    backgroundColor: '#FFD54F',
    borderWidth: 2,
    borderColor: '#E6AC00',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
  },
  secondaryBtnText: {
    color: '#5A3A0A',
    fontSize: 16,
    letterSpacing: 0.4,
  },
  errorText: {
    color: '#FFD4D4',
    fontSize: 14,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  codeInput: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 2,
    borderColor: '#E6D5C3',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 24,
    letterSpacing: 6,
    textAlign: 'center',
    color: '#5A3A0A',
    fontWeight: '800',
  },
  roomCodeHero: {
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#E6D5C3',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  roomCodeLabel: {
    fontSize: 13,
    color: '#6B5344',
    letterSpacing: 1,
  },
  roomCodeValue: {
    fontSize: 36,
    letterSpacing: 8,
    color: '#2A93F4',
  },
  configPillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
  },
  configPill: {
    backgroundColor: '#E8F4FF',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#B3D9FF',
  },
  configPillText: {
    color: '#1565C0',
    fontSize: 12,
    fontWeight: '800',
  },
  playerSlot: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E6D5C3',
    padding: 12,
  },
  playerSlotEmpty: {
    opacity: 0.72,
    borderStyle: 'dashed',
  },
  playerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  playerName: {
    flex: 1,
    fontSize: 16,
    color: '#5A3A0A',
  },
  hostBadge: {
    backgroundColor: '#FFD54F',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#E6AC00',
  },
  hostBadgeText: {
    color: '#5A3A0A',
    fontSize: 10,
    fontWeight: '900',
  },
  kickBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#E74C3C',
    borderWidth: 2,
    borderColor: '#C0392B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kickBtnPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.96 }],
  },
  kickBtnDisabled: {
    opacity: 0.6,
  },
  waitingText: {
    color: '#6B5344',
    fontSize: 13,
    fontStyle: 'italic',
  },
  fontFallbackBold: {
    fontWeight: '800',
  },
  fontFallbackSemi: {
    fontWeight: '600',
  },
});
